In [2]:
import torch
import pandas as pd
import numpy as np

In [3]:

scaler = torch.tensor(7)
print(scaler)

tensor(7)


In [4]:

scaler.ndim

0

In [5]:

scaler.item()

7

In [6]:

vector = torch.tensor([7, 7])

In [7]:
vector,
vector.ndim,
vector.shape

torch.Size([2])

In [8]:

MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:

MATRIX[1]


tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
TENSOR.ndim
TENSOR.shape


torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
Random Tensors are important beacuse they way nerual networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represt the data.


`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1351, 0.1921, 0.0341, 0.7824],
        [0.3691, 0.0482, 0.5874, 0.1824],
        [0.8214, 0.5962, 0.3250, 0.5426]])

In [15]:
random_tensor.ndim

2

In [16]:
# create a rondom tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, coulr channels 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# tensor of all ones
ones = torch.ones(size=(3,4)) 
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tnesors and tensors-like

In [19]:
# torch.arange()
one_to_ten = torch.arange(0,10)

In [20]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor attributes

**NOTE:** Tensor datatypes one of the big errors: 
1. Tensors not right datatype
2. Tensors not the right shape
3. Tensors not on the right device 

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype 
                               device=None, #gpu, cuda, cpu (what device the tensor is on)
                               requires_grad=False) #track gradients of a tensor
float_32_tensor

tensor([3., 6., 9.])

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### manipulating tensors (tensor opearitons)

Tensor operations include: 
* addition
* Subtraction 
* multiplication (element-wise)
* Division 
* matrix Multiplication

In [24]:
# create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [25]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [26]:
# subtact 10 
tensor - 10

tensor([-9, -8, -7])

In [27]:
# try out pytroch inbuilt functiuons
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [28]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication 

Two main ways of perfomring multiplication in nuural netwroks and deep leraning: 
1. Element-wise multipplication 
2. Matrix multiplication ( dot product )

In [29]:
# Element wise multiplication 
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [30]:
# matrix multiplication 
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
tensor

tensor([1, 2, 3])

In [32]:
# matrix by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [33]:
%%time 
value = 0
for i in range(len(tensor)): 
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [34]:
%%time 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Two roles for matrix multiplication: 
`@ = matmul`

1. The **inner dimensions** must match
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**: 
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [35]:
torch.matmul(torch.rand(3,2), torch.rand(3,2)) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2)) 

tensor([[0.3125, 0.9092],
        [0.0933, 0.4745]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
torch.min(x), x.max()

(tensor(1), tensor(91))

In [ ]:
# mean requires float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
torch.sum(x), x.sum() 

(tensor(460), tensor(460))

# Finding postional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin(), x[0]

(tensor(0), tensor(1))

In [ ]:
x.argmax(), x[9]

(tensor(9), tensor(91))

# Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Premute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (beacause a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stack = torch.stack([x, x, x, x], dim=0)
print(x_stack)
x_stack = torch.stack([x, x, x, x], dim=1)
print(x_stack)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [ ]:
# Squeeze - removes all single dimensions or `1's`
print(f"Previous tensor: {x_reshaped}")
print(f"Prevous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Prevous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a speicffic dim 
print(f"Previous target: {x_squeezed}")
print(f"Prevous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) 
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Prevous shape: torch.Size([9])

New Tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.premute - rearranges the dimensions of a traget tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, widht, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order 
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}" ) #[colour channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecing data from tensors)

Indexing with PyTorch is simialr to NumPy

In [ ]:
# new tensor
import torch
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middel bracket (dim = 1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Lets index on the most inner bracket (last dim)
x[0][2][2]

tensor(9)

In [ ]:
x[:, :, 2], x[:, 2, 2]

(tensor([[3, 6, 9]]), tensor([9]))

## PyTorch tensors & NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will it do
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7) 
numpy_tensor = tensor.numpy() 
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In Short a nueral newtork leans: 

`start with random numbers -> tensor operations -> update random numbers to try and make better representaitons of the numbers again agina and again`

To reduce is the concept of a `seed`



In [ ]:
import torch

random_tensor_A = torch.rand(3,4) 
random_tensor_B = torch.rand(3,4) 

print(random_tensor_A)
print(random_tensor_B)

tensor([[0.0754, 0.1809, 0.2030, 0.9194],
        [0.6761, 0.5111, 0.5380, 0.0993],
        [0.0257, 0.2985, 0.1406, 0.3114]])
tensor([[0.1321, 0.6136, 0.1967, 0.4301],
        [0.7022, 0.1095, 0.2243, 0.0904],
        [0.2366, 0.2857, 0.8183, 0.5222]])


In [ ]:
 # Lets make some random but reproducible tensors
RANDOM_SEED = 33
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

tensor([[0.6186, 0.5587, 0.1937, 0.3360],
        [0.2008, 0.6970, 0.6367, 0.1452],
        [0.8213, 0.2365, 0.3702, 0.9168]])
tensor([[0.6186, 0.5587, 0.1937, 0.3360],
        [0.2008, 0.6970, 0.6367, 0.1452],
        [0.8213, 0.2365, 0.3702, 0.9168]])


## Running tensors and pyTorch objects on the GPU's


In [ ]:
import torch

print("Torch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

Torch version: 2.5.1+cu121
CUDA version: 12.1
CUDA available: True
GPU: NVIDIA GeForce RTX 3070


### Device Agnostic Code

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Putting tensors(and models) on the gpu

In [ ]:
# new tensor(defualts to cpu)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to (GPU if availible)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, cant transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To Fix the GPU issue 
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Practice Code

## 2. Create a random tensor with shape (7, 7).


In [68]:
tensor = torch.rand(7,7)
tensor.shape

torch.Size([7, 7])

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor). 


In [69]:
tensor_2 = torch.rand(1,7)
torch.matmul(tensor, tensor_2.T)

tensor([[3.1700],
        [1.7918],
        [2.8558],
        [2.0397],
        [2.3219],
        [2.4240],
        [2.8931]])

## 4. Set the random seed to 0 and do 2 & 3 over again.


In [70]:
RANDOM_SEED = 0 
tensor = torch.rand(7,7)
RANDOM_SEED = 0 
tensor_2 = torch.rand(1,7)

torch.matmul(tensor, tensor_2.T)

tensor([[1.1294],
        [1.9608],
        [1.3544],
        [2.5918],
        [1.9922],
        [1.6717],
        [2.7176]])

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)



In [ ]:
torch.cuda.manual_seed(1234)

## 6. Create two random tensors of shape (2, 3) and send them both to the GPU  (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). 

     

In [72]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

(tensor([[0.3145, 0.5145, 0.5584],
         [0.0901, 0.1350, 0.8637]], device='cuda:0'),
 tensor([[0.0907, 0.1481, 0.6243],
         [0.5862, 0.1984, 0.7537]], device='cuda:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).



In [73]:
tensor_C = torch.matmul(tensor_A, tensor_B.T) 
print(tensor_C)
print(tensor_B.shape, tensor_B.T.shape)

tensor([[0.4533, 0.7073],
        [0.5674, 0.7306]], device='cuda:0')
torch.Size([2, 3]) torch.Size([3, 2])


## 8. Find the maximum and minimum values of the output of 7.



In [74]:
tensor_C.min(), tensor_C.max()

(tensor(0.4533, device='cuda:0'), tensor(0.7306, device='cuda:0'))

## 9. Find the maximum and minimum index values of the output of 7.


In [ ]:
tensor_C.argmin(), tensor_C.argmax()

## 10. Make a random tensor with shape (1, 1, 1, 10) then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.



In [86]:
torch.manual_seed(1234)
tensor = torch.rand(1,1,1,10)
tensor, tensor.shape

(tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
            0.6738, 0.3315]]]]),
 torch.Size([1, 1, 1, 10]))

In [84]:
ten_squez = tensor.squeeze()
ten_squez, ten_squez.shape

(tensor([0.7327, 0.9350, 0.9704, 0.0571, 0.9057, 0.3413, 0.4860, 0.4820, 0.2117,
         0.2507]),
 torch.Size([10]))